services:
  site:
    build:
      context: .
    ports:
      - "4321:4321"
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
            - .astro/
            - .vscode/